name: Build & Test

on: [push]

jobs:
  buildtest:
    runs-on: ubuntu-16.04 #ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        # Lustre
        sudo apt-get install ed module-assistant build-essential libreadline-dev debhelper dpatch automake libsnmp-dev bzip2 quilt linux-headers-generic rsync libtool python-docutils libyaml-dev libselinux-dev pkg-config mpi-default-dev
        # ZFS
        sudo apt-get install build-essential autoconf automake libtool gawk alien fakeroot dkms libblkid-dev uuid-dev libudev-dev libssl-dev zlib1g-dev libaio-dev libattr1-dev libelf-dev linux-headers-$(uname -r) python3 python3-dev python3-setuptools python3-cffi libffi-dev
        # reboot
    - name: Build ZFS
      run: |
        #git clone --branch externally-compressed-data --depth 1 https://github.com/hauke96/zfs.git
        git clone https://github.com/zfsonlinux/zfs.git
        cd zfs
        ./autogen.sh
        ./configure
        make pkg-utils deb-kmod
        sudo dpkg -i *.deb
    - name: Build Lustre
      run: |
        git clone --branch b2_12 --depth 1 git://git.whamcloud.com/fs/lustre-release.git
        cd lustre-release
        sh autogen.sh
        ./configure --disable-ldiskfs
        make debs -j $(nproc)
        #sudo dpkg -i -R debs/
        find . -name '*.deb' 
        sudo apt install $(find . -name '*.deb' | tr '\n' ' ')
    - name: Run Lustre Tests
      run: |
        ls -lah /mnt
        ls -lah /tmp
        zpool version
        cat /proc/mounts
        sudo groupadd -g 500 tests && sudo useradd -u 500 -g 500 runas
        cd /usr/lib/lustre/tests
        # sudo echo -e "FSTYPE=zfs\n$(sudo cat cfg/local.sh)" > cfg/local.sh
        sudo sed -i '1s/^/FSTYPE=zfs\n/' cfg/local.sh 
        sudo VERBOSE=true ./llmount.sh
        sudo ./auster -v -r sanity.sh --only 0a
        
      
