name: Build & Test

on: [push]

jobs:
  buildtest:
    runs-on: ubuntu-16.04 #ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        lsmod | less
        ls -lah /lib/modules/
        ls -lah /lib/modules/*/kernel/zfs/
        ls -lah /lib/modules/*/kernel/spl/
        sudo rm -rf /lib/modules/*/kernel/zfs/
        sudo rm -rf /lib/modules/*/kernel/spl/
        depmod -a
        
        sudo apt-get update
        #sudo apt-get upgrade
        # Lustre
        sudo apt-get install ed module-assistant build-essential libreadline-dev debhelper dpatch automake libsnmp-dev bzip2 quilt linux-headers-generic rsync libtool python-docutils libyaml-dev libselinux-dev pkg-config mpi-default-dev
        # ZFS
        sudo apt-get install build-essential autoconf automake libtool gawk alien fakeroot dkms libblkid-dev uuid-dev libudev-dev libssl-dev zlib1g-dev libaio-dev libattr1-dev libelf-dev linux-headers-$(uname -r) python3 python3-dev python3-setuptools python3-cffi libffi-dev
        # reboot
    - name: Build ZFS
      run: |
        #git clone --branch externally-compressed-data --depth 1 https://github.com/hauke96/zfs.git
        git clone https://github.com/zfsonlinux/zfs.git
        cd zfs
        ./autogen.sh
        ./configure
        make pkg-utils deb-kmod
        ls -lah *.deb
        sudo dpkg -i *.deb
    - name: Build Lustre
      run: |
        git clone --branch b2_12 --depth 1 git://git.whamcloud.com/fs/lustre-release.git
        cd lustre-release
        sh autogen.sh
        ./configure --disable-ldiskfs
        make debs -j $(nproc)
        #sudo dpkg -i -R debs/
        find . -name '*.deb' 
        sudo apt install $(find . -name '*.deb' | tr '\n' ' ')
    - name: Run Lustre Tests
      run: |
        ls -lah /mnt
        ls -lah /tmp
        sudo depmod -a
        sudo modprobe zfs -v
        zpool version
        cat /proc/mounts
        sudo groupadd -g 500 tests && sudo useradd -u 500 -g 500 runas
        cd /usr/lib/lustre/ && patch -p1 << EOF
        --- lustre/tests/test-framework.sh  2019-10-06 17:33:49.114766351 +0200
        +++ lustre/tests/test-framework_notouch.sh  2019-10-08 18:14:28.778186388 +0200
        @@ -4426,7 +4426,7 @@
            # touch "device" in case it is a loopback file for testing and needs to
            # be created. mkfs.lustre doesn't do this to avoid accidentally writing
            # to non-existent files in /dev if the admin made a typo during setup
        -   __touch_device mgs
        +   #__touch_device mgs
         
            add mgs $(mkfs_opts mgs $(mgsdevname)) $(mountfs_opts mgs) --reformat \
                $(mgsdevname) $(mgsvdevname) ${quiet:+>/dev/null} || exit 10
        @@ -4442,7 +4442,7 @@
            echo "Format mds$num: $(mdsdevname $num)"
            reformat_external_journal mds$num
         
        -   __touch_device mds $num
        +   #__touch_device mds $num
         
            add mds$num $(mkfs_opts mds$num $(mdsdevname ${num})) \
                $(mountfs_opts mds$num) --reformat $(mdsdevname $num) \
        @@ -4458,7 +4458,7 @@
            echo "Format ost$num: $(ostdevname $num)"
            reformat_external_journal ost$num
         
        -   __touch_device ost $num
        +   #__touch_device ost $num
         
            add ost$num $(mkfs_opts ost$num $(ostdevname ${num})) \
                $(mountfs_opts ost$num) --reformat $(ostdevname $num) \
        EOF
        cd /usr/lib/lustre/tests
        sudo sed -i '1s/^/FSTYPE=zfs\n/' cfg/local.sh 
        sudo VERBOSE=true ./llmount.sh
        sudo ./auster -v -r sanity.sh --only 0a
        
