name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Dependencies
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install ed module-assistant build-essential libreadline-dev debhelper dpatch automake libsnmp-dev bzip2 quilt linux-headers-generic rsync libtool python-docutils libyaml-dev libselinux-dev pkg-config mpi-default-dev
        sudo apt-get install zfs-dkms
        # reboot
        git clone --branch b2_12 --depth 1 git://git.whamcloud.com/fs/lustre-release.git
        cd lustre-release
        sh autogen.sh
        ./configure --disable-ldiskfs
        make debs
      
