name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        # Lustre
        sudo apt-get install ed module-assistant build-essential libreadline-dev debhelper dpatch automake libsnmp-dev bzip2 quilt linux-headers-generic rsync libtool python-docutils libyaml-dev libselinux-dev pkg-config mpi-default-dev
        # ZFS
        sudo apt-get install build-essential autoconf automake libtool gawk alien fakeroot dkms libblkid-dev uuid-dev libudev-dev libssl-dev zlib1g-dev libaio-dev libattr1-dev libelf-dev linux-headers-$(uname -r) python3 python3-dev python3-setuptools python3-cffi libffi-dev
        # reboot
    - name: Build ZFS
      run: |
        git clone --branch externally-compressed-data --depth 1 https://github.com/hauke96/zfs.git
        cd zfs
        ./autogen.sh
        ./configure
        make deb
        sudo apt install *.deb
    - name: Build Lustre
      run: |
        git clone --branch b2_12 --depth 1 git://git.whamcloud.com/fs/lustre-release.git
        cd lustre-release
        sh autogen.sh
        ./configure --disable-ldiskfs
        make debs
        sudo apt install *.deb
        
      
