name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build ZFS & Lustre
      uses: ./.github/actions/build
    - name: Run Lustre Test
      run: |
        ls /var/
        sudo groupadd -g 500 tests && sudo useradd -u 500 -g 500 runas
        cd /var/lib/lustre/tests
        VERBOSE=true ./llmount.sh
        ./auster -v -r sanity.sh --only 0a
        
